version: '3.8'
services:
  redis:
    image: redis
    container_name: redis-dev
    restart: always
    ports:
      - 6379:6379

  # root user = root
  mysql:
    image: mysql
    container_name: mysql-dev
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=test-db
      - MYSQL_ROOT_PASSWORD=password
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
